"""TOPIX500(= TOPIX Core30 + Large70 + Mid400)の銘柄コードを JPX 公式データから生成する。

JPX が公開する「東証上場銘柄一覧(data_j.xls)」には各銘柄の「規模区分」があり、
TOPIX Core30 / Large70 / Mid400 の3区分の和がちょうど TOPIX500 にあたる。
これを抽出して `stock_analyzer/data/universe.txt`(スイング候補の分析ユニバース)を作る。

依存: pandas と xls を読む xlrd(実行時ではなく、このスクリプトを動かす時だけ必要)。
使い方: python scripts/build_universe.py
JPX の構成銘柄は入れ替わるので、たまに再実行して universe.txt を更新する。
"""

from __future__ import annotations

import datetime
import io
import sys
import urllib.request
from pathlib import Path

JPX_XLS_URL = (
    "https://www.jpx.co.jp/markets/statistics-equities/misc/"
    "tvdivq0000001vg2-att/data_j.xls"
)
# TOPIX500 = この3つの規模区分の和(スモールは含めない)。
TOPIX500_SIZES = {"TOPIX Core30", "TOPIX Large70", "TOPIX Mid400"}

OUTPUT = Path(__file__).resolve().parent.parent / "stock_analyzer" / "data" / "universe.txt"


def fetch_codes() -> list[str]:
    import pandas as pd

    req = urllib.request.Request(JPX_XLS_URL, headers={"User-Agent": "Mozilla/5.0"})
    raw = urllib.request.urlopen(req, timeout=120).read()
    df = pd.read_excel(io.BytesIO(raw))

    # ヘッダーは Shift-JIS で文字化けするため、位置で参照する(列順は安定):
    #   0:日付 1:コード 2:銘柄名 3:市場区分 ... 9:規模区分
    code_col = df.columns[1]
    size_col = df.columns[9]

    picked = df[df[size_col].isin(TOPIX500_SIZES)]
    codes = []
    for value in picked[code_col].tolist():
        code = str(value).strip().upper()
        if code and code != "NAN":
            codes.append(f"{code}.T")
    # 重複排除しつつ元の順(コード昇順)を保つ
    seen: set[str] = set()
    unique = [c for c in codes if not (c in seen or seen.add(c))]
    unique.sort()
    return unique


def main() -> None:
    codes = fetch_codes()
    if len(codes) < 400:
        print(f"想定より少ない銘柄数({len(codes)})です。JPXの様式変更の可能性。中止します。", file=sys.stderr)
        raise SystemExit(1)

    today = datetime.date.today().isoformat()
    header = [
        "# TOPIX500 constituent tickers (TOPIX Core30 + Large70 + Mid400), one per line.",
        "# Auto-generated by scripts/build_universe.py from the JPX listed-issues file.",
        f"# Source: {JPX_XLS_URL}",
        f"# Generated: {today}  Count: {len(codes)}",
        "# Company names are fetched live from yfinance, so only valid codes are needed here.",
    ]
    OUTPUT.write_text("\n".join(header + codes) + "\n", encoding="utf-8")
    print(f"{OUTPUT} に {len(codes)} 銘柄を書き出しました")


if __name__ == "__main__":
    main()
